apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-{{ .Values.userID }}{{ .Values.nameSuffix }}
  namespace: showks
  labels:
    class: {{ .Chart.Name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/ssl-services: "{{ .Chart.Name }}-{{ .Values.userID }}{{ .Values.nameSuffix }}"
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
      - {{ .Chart.Name }}-{{ .Values.userID }}{{ .Values.vhostDomain }}
      secretName: tls-certificate
  rules:
  - host: {{ .Chart.Name }}-{{ .Values.userID }}{{ .Values.vhostDomain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Chart.Name }}-{{ .Values.userID }}{{ .Values.nameSuffix }}
          servicePort: 8080
