apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-{{ .Values.userID }}{{ .Values.nameSuffix }}
  namespace: showks
  labels:
    class: {{ .Chart.Name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: {{ .Chart.Name }}-{{ .Values.userID }}{{ .Values.vhostDomain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Chart.Name }}-{{ .Values.userID }}{{ .Values.nameSuffix }}
          servicePort: 8080
